#!/system/bin/sh

/system/bin/log "Start permissions script..."
/system/xbin/su -c "chmod 0666 /dev/MTK_SMI"
/system/xbin/su -c "chown bluetooth:bluetooth /dev/stpbt"
/system/xbin/su -c "chown bluetooth:bluetooth /dev/ttyGS0"
/system/xbin/su -c "chmod 0666 /dev/stpbt"
/system/xbin/su -c "chmod 0666 /dev/ttyGS0"
