#!/system/bin/sh
PATH=/sbin:/system/sbin:/system/bin:/system/xbin
FILE="/data/firstboot"

if [ -f $FILE  ]; then
  echo "Not the first boot"
else
  sleep 120
  # Keyboard at first boot
  settings --user 0 put secure show_ime_with_hard_keyboard 1
  # Bluetooth at first boot
  settings --user 0 put global bluetooth_on 1
  # Screen timeout
  settings --user 0 put system screen_off_timeout 900000
  # Bluetooth at first boot
  service call bluetooth_manager 8
  # No status bar
  settings --user 0 put global policy_control immersive.status=*
  echo 1 > $FILE
fi

# Double check
setenforce 0

# Remove Amazon logd stuff
rm -rf /dev/logd

# Disable FireOS unused exports
unset AMAZON_EXTRA_RESOURCE_LIST

# Change some "/dev/" permissions
chmod 0666 /dev/kmsg
chmod 0666 /dev/MTK_SMI
chmod 0644 /dev/mtk_cmdq
