#!/system/bin/sh

# This program is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the License, 
# or (at your option) any later version.This program is distributed in the hope that it will be useful, but 
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.You should have 
# received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.

# Specify the program variables.
LOG_DIR="/data/local/tmp/logdump"
SDCARD_LOG="/sdcard/logdump"
command="$1"

# Help function.
function -h {
echo " -c  Cleanup old logs"
echo " -b  Take bugreport"
echo " -l  Take logcat"
echo " -d  Take dmesg"
echo " -h  Show help"
echo " -i  idme print"
echo " -s  Take dumpsys log (i.e 'dumpsys bluetooth_manager')"
}

# Dumpsys function.
function -s {
echo "Type the service name to debug:"
read service
dumpsys $service > $LOG_DIR/dumpsys_$service.log
cp $LOG_DIR/dumpsys_$service.log $SDCARD_LOG/
}

# Cleanup function.
function -c {
rm $LOG_DIR/* > /dev/null 2>&1
rm /sdcard/logdump/* > /dev/null 2>&1
}

# Logcat function.
function -l {
timeout 10 logcat > $LOG_DIR/logcat.log
cp $LOG_DIR/logcat.log $SDCARD_LOG/logcat.log
}

# Dmesg function.
function -d {
dmesg > $LOG_DIR/dmesg.log
cp $LOG_DIR/dmesg.log $SDCARD_LOG/dmesg.log
}

# Idme function.
function -i {
idme print > $LOG_DIR/idme.log
cp $LOG_DIR/idme.log $SDCARD_LOG/idme.log
}

# Bugreport function.
function -b {
timeout 10 bugreport > $LOG_DIR/bugreport.log
cp $LOG_DIR/bugreport.log $SDCARD_LOG/bugreport.log
}

# Create log folders. If they're already present, redirect stderr to stdout to avoid errors.
mkdir $LOG_DUMP > /dev/null 2>&1
mkdir $SDCARD_LOG > /dev/null 2>&1

# Execute the selected command.
$command
