#!/system/bin/sh

# This program is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the License, 
# or (at your option) any later version.This program is distributed in the hope that it will be useful, but 
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.You should have 
# received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.

LOG_DIR="/data/local/tmp/logdump"
command="$1"

function -h {
echo " -c  Cleanup old logs"
echo " -b  Take bugreport"
echo " -l  Take logcat"
echo " -d  Take dmesg"
echo " -h  Show help"
echo " -i  idme print"
}

function -c {
rm $LOG_DIR/*
rm /sdcard/logdump/*
}

function -l {
timeout 10 logcat > $LOG_DIR/logcat.log
cp $LOG_DIR/logcat.log /sdcard/logdump/
}

function -d {
dmesg > $LOG_DIR/dmesg.log
cp $LOG_DIR/dmesg.log /sdcard/logdump/dmesg.log
}

function -i {
idme print > $LOG_DIR/idme.log
cp $LOG_DIR/idme.log /sdcard/logdump/idme.log
}

function -b {
timeout 10 bugreport > $LOG_DIR/bugreport.log
cp $LOG_DIR/bugreport.log /sdcard/logdump/bugreport.log
}

function -a {
echo "Taking logcat..."
-l
echo "Taking dmesg..."
-d
echo "Getting idme info..."
-i
echo "Taking bugreport"
-b
echo "All done!"
}

if [ -e "/data/local/tmp/logdump" ] || [ -e "/sdcard/logdump" ]
then
    $command
else
    mkdir /data/local/tmp/logdump
    mkdir /sdcard/logdump
fi
